In [ ]:

!pip install torch==2.2.2 torchtext==0.6.0
!pip install spacy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 118.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 93.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 44.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:

import torch
import torchtext
print(f"Torch: {torch.__version__}")
# print(f"TorchText: {torchtext.__version__}")


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.12/dist-package

Torch: 2.2.2+cu121


In [ ]:
!python -m spacy download de
!python -m spacy download en


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/local/lib/python3.12/dist-packages/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/usr/local/lib/python3.12/dist-packages/spacy/errors.py", line 3, in <module>
    from .compat import Literal
  File "/usr/local/lib/python3.12/dist-packages/spacy/compat.py", line 5, in <module>
    from thinc.

In [ ]:
import torch
import torch.nn as nn

class Transformer(nn.Module):
    def __init__(
            self,
            embed_size,
            src_vocab_size,
            trg_vocab_size,
            src_pad_idx,
            num_heads,
            num_encoder_layers,
            num_decoder_layers,
            forward_expansion,
            dropout,
            max_length,
            device
    ):
        super(Transformer, self).__init__()
        self.src_embedding = nn.Embedding(src_vocab_size, embed_size)
        self.src_positional_embedding = nn.Embedding(max_length, embed_size)
        self.trg_embedding = nn.Embedding(trg_vocab_size, embed_size)
        self.trg_positional_embedding = nn.Embedding(max_length, embed_size)
        self.device = device

        self.transformer = nn.Transformer(
            embed_size,
            num_heads,
            num_encoder_layers,
            num_decoder_layers,
            forward_expansion,
            dropout,
        )
        self.fc_out = nn.Linear(embed_size, trg_vocab_size)
        self.dropout = nn.Dropout(dropout)
        self.src_pad_idx = src_pad_idx

    def make_src_mask(self, src):
        # src   => (src_len, N)
        # mask  => (N, src_len)
        return src.transpose(0, 1) == self.src_pad_idx

    def forward(self, src, trg):
        src_seq_length, N = src.shape
        trg_seq_length, N = trg.shape

        src_postions = (
            torch.arange(0, src_seq_length).unsqueeze(1).expand(src_seq_length, N).to(self.device)
        )

        trg_postions = (
            torch.arange(0, trg_seq_length).unsqueeze(1).expand(trg_seq_length, N).to(self.device)
        )

        embed_src = self.dropout(
            self.src_embedding(src) + self.src_positional_embedding(src_postions)
        )

        embed_trg = self.dropout(
            self.src_embedding(trg) + self.src_positional_embedding(trg_postions)
        )

        src_padding_mask = self.make_src_mask(src)
        trg_padding_mask = self.transformer.generate_square_subsequent_mask(trg_seq_length).to(self.device)

        out = self.transformer(
            embed_src,
            embed_trg,
            src_key_padding_mask=src_padding_mask,
            tgt_mask=trg_padding_mask
        )

        return self.fc_out(out)


In [ ]:
import torch
import spacy
from torchtext.data.metrics import bleu_score
import sys


def translate_sentence(model, sentence, german, english, device, max_length=50):
    # Load german tokenizer
    spacy_ger = spacy.load("de_core_news_sm")

    # Create tokens using spacy and everything in lower case (which is what our vocab is)
    if type(sentence) == str:
        tokens = [token.text.lower() for token in spacy_ger(sentence)]
    else:
        tokens = [token.lower() for token in sentence]

    # Add <SOS> and <EOS> in beginning and end respectively
    tokens.insert(0, german.init_token)
    tokens.append(german.eos_token)

    # Go through each german token and convert to an index
    text_to_indices = [german.vocab.stoi[token] for token in tokens]

    # Convert to Tensor
    sentence_tensor = torch.LongTensor(text_to_indices).unsqueeze(1).to(device)

    outputs = [english.vocab.stoi["<sos>"]]
    for i in range(max_length):
        trg_tensor = torch.LongTensor(outputs).unsqueeze(1).to(device)

        with torch.no_grad():
            output = model(sentence_tensor, trg_tensor)

        best_guess = output.argmax(2)[-1, :].item()
        outputs.append(best_guess)

        if best_guess == english.vocab.stoi["<eos>"]:
            break

    translated_sentence = [english.vocab.itos[idx] for idx in outputs]
    # remove start token
    return translated_sentence[1:]


def bleu(data, model, german, english, device):
    targets = []
    outputs = []

    for example in data:
        src = vars(example)["src"]
        trg = vars(example)["trg"]

        prediction = translate_sentence(model, src, german, english, device)
        prediction = prediction[:-1]  # remove <eos> token

        targets.append([trg])
        outputs.append(prediction)

    return bleu_score(outputs, targets)


def save_checkpoint(state, filename="my_checkpoint.pth.tar"):
    print("=> Saving checkpoint")
    torch.save(state, filename)


def load_checkpoint(checkpoint, model, optimizer):
    print("=> Loading checkpoint")
    model.load_state_dict(checkpoint["state_dict"])
    optimizer.load_state_dict(checkpoint["optimizer"])

In [ ]:
import os
import requests

# 1. Create the directory torchtext expects
os.makedirs('.data/multi30k', exist_ok=True)

# 2. Define the URLs for the dataset (using a reliable mirror)
urls = [
    ('https://raw.githubusercontent.com/neychev/small_DL_repo/master/datasets/Multi30k/train.de', 'train.de'),
    ('https://raw.githubusercontent.com/neychev/small_DL_repo/master/datasets/Multi30k/train.en', 'train.en'),
    ('https://raw.githubusercontent.com/neychev/small_DL_repo/master/datasets/Multi30k/val.de', 'val.de'),
    ('https://raw.githubusercontent.com/neychev/small_DL_repo/master/datasets/Multi30k/val.en', 'val.en'),
    ('https://raw.githubusercontent.com/neychev/small_DL_repo/master/datasets/Multi30k/test2016.de', 'test.de'),
    ('https://raw.githubusercontent.com/neychev/small_DL_repo/master/datasets/Multi30k/test2016.en', 'test.en')
]

# 3. Download the files
print("Downloading Multi30k dataset manually...")
for url, filename in urls:
    response = requests.get(url)
    with open(f'.data/multi30k/{filename}', 'wb') as f:
        f.write(response.content)
    print(f"Downloaded {filename}")

print("Download complete. You can now run the Multi30k.splits command.")

Downloaded train.de
Downloaded train.en
Downloaded val.de
Downloaded val.en
Downloaded test.de
Downloaded test.en
Download complete. You can now run the Multi30k.splits command.


In [ ]:
import os

# Rename the test files to match the expected 'test2016' filename
try:
    os.rename('.data/multi30k/test.de', '.data/multi30k/test2016.de')
    os.rename('.data/multi30k/test.en', '.data/multi30k/test2016.en')
    print("Files renamed successfully.")
except FileNotFoundError:
    print("Files not found. Please ensure the download script from the previous step ran correctly.")

Files renamed successfully.


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import spacy
from torch.nn.utils import clip_grad_norm

from torch.utils.tensorboard import SummaryWriter
from torchtext.datasets import Multi30k
from torchtext import data

spacy_ger = spacy.load('de_core_news_sm')
spacy_eng = spacy.load('en_core_web_sm')

def tokenize_ger(text):
    return [token.text for token in spacy_ger.tokenizer(text)]

def tokenize_end(text):
    return [token.text for token in spacy_eng.tokenizer(text)]

german = data.Field(tokenize=tokenize_ger, lower=True, init_token="<sos>", eos_token="<eos>")
english = data.Field(tokenize=tokenize_end, lower=True, init_token="<sos>", eos_token="<eos>")

train_data, valid_data, test_data = Multi30k.splits(
    exts=(".de", ".en"), fields=(german, english)
)

german.build_vocab(train_data, max_size=10000, min_freq=2)
english.build_vocab(train_data, max_size=10000, min_freq=2)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
load_model = False
save_model = True

# Training hyperparameters
num_epochs = 10
lr = 3e-4
bs = 32

# Model hyperparameters
src_vocab_size      = len(german.vocab)
trg_vocab_size      = len(english.vocab)
embed_size          = 512
num_heads           = 8
num_encoder_layers  = 3
num_decoder_layers  = 3
dropout             = 0.1
max_length          = 100
forward_expansion   = 4
src_pad_idx         = english.vocab.stoi["<pad>"]

# Tensorboard
writer = SummaryWriter("runs/loss_plot")
step = 0

train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits(
    (train_data, valid_data, test_data),
    batch_size = bs,
    sort_within_batch = True,
    sort_key = lambda x: len(x.src),
    device = device
)

model = Transformer(
    embed_size,
    src_vocab_size,
    trg_vocab_size,
    src_pad_idx,
    num_heads,
    num_encoder_layers,
    num_decoder_layers,
    forward_expansion,
    dropout,
    max_length,
    device
).to(device)

optimizer = optim.Adam(model.parameters(), lr=lr)

criterion = nn.CrossEntropyLoss(ignore_index=src_pad_idx)

if load_model:
    load_checkpoint(torch.load("my_checkpoint.pth.ptar"), model, optimizer)

sentence =  "ein pferd geht unter einer brücke neben einem boot."

for epoch in range(num_epochs):
    print(f"[Epoch {epoch} / {num_epochs}")

    # if save_model:
    #     checkpoint = {
    #         "state_dict" : model.state_dict(),
    #         "optimizer" : optimizer.state_dict()
    #     }

    #     save_checkpoint(checkpoint)

    model.eval()
    translated_sentence = translate_sentence(
        model, sentence, german, english, device, max_length = max_length
    )

    print(f"Translated example sentence \n {translated_sentence}")

    model.train()

    for batch_idx, batch in enumerate(train_iterator):
        inp_data = batch.src.to(device)
        target = batch.trg.to(device)
        output = model(inp_data, target[:-1])

        output = output.reshape(-1, output.shape[2])
        target = target[1:].reshape(-1)
        optimizer.zero_grad()

        loss = criterion(output, target)
        loss.backward()
        torch.nn.utils.clip_grad_norm(model.parameters(), max_norm=1)
        print("==="*50)
        print(inp_data)
        print(target)
        print(output)
        print(loss.item())
        print("==="*50)

        optimizer.step()
        break
        writer.add_scalar("Training loss", loss, global_step=step)
        step += 1

score = bleu(test_data, model, german, english, device)
print(f"Bleu score {score*100:.2f}")


[Epoch 0 / 10
Translated example sentence 
 ['<eos>']
tensor([[2],
        [0],
        [0],
        [0],
        [0],
        [3]], device='cuda:0')
tensor([0, 0, 0, 0, 3], device='cuda:0')
tensor([[-0.5063, -0.2500,  0.2140,  0.8672],
        [-0.5624, -0.4384,  0.0311,  0.5513],
        [-0.3881, -0.5932,  0.6842,  0.5972],
        [-0.8363, -1.0095,  0.5097,  0.6192],
        [-0.4802, -0.5512,  0.5963,  0.4368]], device='cuda:0',
       grad_fn=<ViewBackward0>)
1.888643503189087
[Epoch 1 / 10


/tmp/ipython-input-2841576392.py:117: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  torch.nn.utils.clip_grad_norm(model.parameters(), max_norm=1)


Translated example sentence 
 ['<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
tensor([[2],
        [0],
        [0],
        [0],
        [0],
    

In [ ]:
!pip install numpy
